### PR TITLE
208 dispose pipe automatically when closing executionhelper or visa

### LINKED ISSUE #193: Make ExecutionHelper not crash on second run of a StepBro script

### PR DESCRIPTION
**Pull request by MolaeMaceria**
Fix #193 

Fix various errors regarding ExecutionHelper and VISA
Clean-up

### CODE REVIEW

File: source/StepBro.VISABridge/MainForm.cs [hunk 1]
```diff
@@ -232,6 +233,11 @@ private void MainForm_Load(object sender, EventArgs e)
         {
             string[] args = Environment.GetCommandLineArgs();
 
+            FormClosing += (s, evt) =>
```
Comment (JanJorgensen) [inline source/StepBro.VISABridge/MainForm.cs:236]: Replace with override of OnFormClosing. Events are for external objects.

**Review by JanJorgensen — APPROVED** [review]
